### ISSUE TITLE
Change "Remix in Figma" to "Edit in Figma"

### ISSUE THREAD

**Issue by zachlatta** [hackclub/jams#174]
Watching someone go through a Jam today. They said "I wish I could edit these slides".

I think using the word "Edit" will be clearer than using "Remix" for people who haven't used Figma before.

**Comment by zachlatta** [comment]
I also think "Play in Figma" should be renamed to "Present" for clarity.

**Comment by SerenityUX** [comment]
Great feedback & agree, edited. 
<img width="643" alt="Screenshot 2023-09-17 at 9 22 14 PM" src="https://github.com/hackclub/jams/assets/95105859/a9ac3f32-863c-44f3-bafc-6a634024b662">
