### ISSUE TITLE
Batch Jam homepage parts unintuitive

### ISSUE THREAD

**Issue by karmanyaahm** [hackclub/jams#180]
My jam test subject was trying to click on 1 and 2. They thought 3,4,5,6 was a "suggestions" or "see more like this" type of thing. Maybe there should be a "Parts:" heading or the "Part 1" overlay should be made permanent, not only on hover. 

![image](https://github.com/hackclub/jams/assets/32671690/eefe15bd-9199-43bb-a41d-3c41333c2ac4)

**Comment by karmanyaahm** [comment]
![image](https://github.com/hackclub/jams/assets/32671690/ab7fcfcb-08e3-4d47-a39d-54844bfe5531)

**Comment by SerenityUX** [comment]
fixed! TYSM!
