### ISSUE TITLE
let's have links to downloadable posters/flyers for jams

### ISSUE THREAD

**Issue by karamassie** [hackclub/jams#190]
Can we have a PDF and Figma file that ppl can download to help promote their jams?
Sprig for each sprig jam
onboard likewise

**Comment by SerenityUX** [comment]
Hey Kara! This feature exists. The poster pdf or figma just needs to be attached to the poster property. Here's an example of a Jam that has a poster:
https://jams.hackclub.com/jam/story-game


I'll add the Sprig & Onboard posters.
