### ISSUE TITLE
Faces too big

### ISSUE THREAD

**Issue by maxwofford** [hackclub/jams#196]
For some reason the author's avatar on batch pages is huge
<img width="1265" alt="Screenshot 2024-01-10 at 10 56 24" src="https://github.com/hackclub/jams/assets/5891442/97527113-73f9-4ccd-a8d0-09d45f93e515">
<img width="1263" alt="Screenshot 2024-01-10 at 10 56 32" src="https://github.com/hackclub/jams/assets/5891442/1b879735-b68e-463a-896d-98fa7b0c564a">

**Comment by BrightTheBackpack** [comment]
what browser are you on? I can't seem to replicate this

**Comment by maxwofford** [comment]
I think this was fixed since I filled the issue! I'm not seeing the bug anymore.
