### ISSUE TITLE
Update link to "Schematics: in a minute"

### ISSUE THREAD

**Issue by maxwofford** [hackclub/jams#201]
Previously this video was hosted on my personal youtube account. It's now at https://youtu.be/lEcN3JnTge4

**Comment by jaspermayone** [comment]
@SerenityUX can you add this to your to-do list?

**Comment by jaspermayone** [comment]
Hey @maxwofford, where might I find the file to update this in? (what jam was it)

**Comment by shayanm4lik** [comment]
@maxwofford Is this updated?

**Comment by BrightTheBackpack** [comment]
Closing because looks like it has been updated
