### ISSUE TITLE
Nested pulldowns don't work

### ISSUE THREAD

**Issue by ajsirota** [hackclub/jams#220]
Pull down the `I'm a little lost` pulldown [here](https://jams.hackclub.com/jam/kaboom-game#Add%20another%20level!) , then try to open one of the pulldowns inside. It doesn't work, because clicking anywhere inside a pulldown causes it to close.

**Comment by BrightTheBackpack** [comment]
relates to #200

**Comment by ajsirota** [comment]
oh ok, i'll close this so we don't have a dupe
